config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: 20}
  validates :password, presence: true, length: {minimum: 6}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = t ".danger"
      render :new
    end
  end

  def new
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:info] = t ".info"
      redirect_to root_url
    else
      render :new
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <hr>
  <p><%= t ".developer" %></p>
  <ul>
    <li><%= link_to t(:about), about_path %></li>
    <li><%= link_to t(:help), help_path %></li>
    <li><%= link_to t(:contact), contact_path %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <%= link_to t(:site_name), root_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li><%= link_to t(:logout), logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to t(:sign_up), signup_path %></li>
          <li><%= link_to t(:login), login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div class="show_error">
    <div class="alert alert-danger">
      <%= t(".contain_error") %> <%= pluralize object.errors.count, t(:error) %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1><%= t :about %></h1>

app/views/static_pages/contact.html.erb
<h1><%= t ".contact" %></h1>

app/views/static_pages/help.html.erb
<h1><%= t :help %></h1>

app/views/static_pages/home.html.erb
<%= provide :title, t(:site_name) %>
<div class="jumbotron">
  <h1><%= t :site_name %></h1>
  <p><%= t :lorem %></p>
</div>

app/views/users/new.html.erb
<%= provide :title, t(:sign_up) %>
<h1><%= t :sign_up %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render "shared/error", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t(:sign_up).upcase!, class: "btn btn-primary", id: "btn_sign_up" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, t(:profile) %>
<h1><%= current_user.name %></h1>